[package]
name = "simple-socks-rust"
version = "0.1.0"
edition = "2024"
description = "Minimal no-auth SOCKS4/5 proxy server"

[dependencies]
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
    "time",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
