name: Build Release Binaries

on:
  push:
    tags:
      - 'v*' # Dijalankan setiap kali Anda push tag versi, contoh: v1.0.0
  workflow_dispatch: # Memungkinkan trigger manual dari tab Actions di GitHub

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # x64 standar (Static musl)
          - target: x86_64-unknown-linux-musl
            artifact_name: socks-server-x86_64-musl

          # OpenWrt / Router ARM64
          - target: aarch64-unknown-linux-musl
            artifact_name: socks-server-aarch64-musl

          # OpenWrt / Router ARMv7
          - target: armv7-unknown-linux-muslebihf
            artifact_name: socks-server-armv7-musl
          
          # Linksys EA4500 / Marvell Kirkwood (ARMv5TE soft-float)
          - target: armv5te-unknown-linux-musleabi
            artifact_name: socks-server-armv5te-musl

          # OpenWrt / Router MIPS (Little Endian - cth: MediaTek MT7621)
          - target: mipsel-unknown-linux-musl
            artifact_name: socks-server-mipsel-musl

          # OpenWrt / Router MIPS (Big Endian - cth: Atheros AR71XX)
          - target: mips-unknown-linux-musl
            artifact_name: socks-server-mips-musl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # Menginstall 'cross' untuk manajemen Docker cross-compilation
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/socks-server